spring:
  application:
    name: SAVINGS-SAVINGS-ACCOUNT-INFO
  datasource:
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:35457/banking_db
    username: root
    password: WChVOxlxAIfxdhzJCjHSKEPjpsJLABeG
    driver-class-name: com.mysql.cj.jdbc.Driver


  main:
    allow-circular-references: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8085/eureka}

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8196
